name: Build mpkg project using muddler

on:
  push:
    paths: mpkg/*
  pull_request:
    paths: mpkg/*

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Muddle
        uses: demonnic/build-with-muddler@main
        with:
          workingDir: mpkg/

      - name: Copy to packages directory
        run: |
          ls -al mpkg/build/mpkg.mpackage
          ls -al packages/
          cp -v mpkg/build/mpkg.mpackage packages/

      - name: Upload Artifact
        uses: actions/upload-artifact@master
        with:
          name: mpkg.mpackage
          path: packages/mpkg.mpackage
          overwrite: true
