name: Build mpkg project using muddler

on:
#  push:
#    paths: mpkg/*
#  pull_request:
#    paths: mpkg/*

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Muddle
        uses: demonnic/build-with-muddler@main
        with:
          workingDir: mpkg/

      - name: Upload Artifact
        uses: actions/upload-artifact@master
        with:
          name: mpkg.mpackage
          path: build/tmp/mpkg.mpackage
          overwrite: true
