name: Update core packages

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * fri'

jobs:
  update-core-packages:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'Mudlet' }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: development

      - name: Download deleteOldProfiles package
        uses: carlosperate/download-file-action@v2.0.2
        with:
          file-url: https://raw.githubusercontent.com/Mudlet/Mudlet/development/src/deleteOldProfiles.mpackage
          file-name: deleteOldProfiles.mpackage
          location: packages/

      - name: Download echo package
        uses: carlosperate/download-file-action@v2.0.2
        with:
          file-url: https://raw.githubusercontent.com/Mudlet/Mudlet/development/src/echo.mpackage
          file-name: echo.mpackage
          location: packages/

      - name: Download enable-accessibility package
        uses: carlosperate/download-file-action@v2.0.2
        with:
          file-url: https://raw.githubusercontent.com/Mudlet/Mudlet/development/src/enable-accessibility.mpackage
          file-name: enable-accessibility.mpackage
          location: packages/

      - name: Download run-lua-code package
        uses: carlosperate/download-file-action@v2.0.2
        with:
          file-url: https://raw.githubusercontent.com/Mudlet/Mudlet/development/src/run-lua-code.mpackage
          file-name: run-lua-code.mpackage
          location: packages/

      - name: Check for changes
        id: check-changes
        run: |
          git diff --quiet packages/ || echo "changes=true" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        if: steps.check-changes.outputs.changes == 'true'
        with:
          token: ${{ secrets.GH_PAT_UPDATE_3RDPARTY }}
          add-paths: packages/
          branch: update-core-packages
          commit-message: "(autocommit) Updated core packages to latest versions"
          title: "Infrastructure: Update core packages to latest versions"
          body: |
            #### Brief overview of PR changes/additions
            🔄 An automated PR to update the core packages to their latest versions.

            #### Other info
            _update triggered by ${{ github.ref }} ${{ github.sha }}_
          author: mudlet-machine-account <mudlet-machine-account@users.noreply.github.com>
